kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-persistvol-1gb-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage-class
  resources:
    requests:
      storage: 1Gi
